name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main
    workflow_dispatch: # This allows manual triggering of the workflow.
    schedule:
        - cron: "0 0 * * *" # This schedules the workflow to run nightly at 00:00 UTC.

permissions:
    contents: write

jobs:
    deploy:
        name: Build to docs branch
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: yarn

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            # Pull the latest doc pages from the API repository
            - name: Checkout API repository
              uses: actions/checkout@v3
              with:
                  repository: causalabs/causadb-server
                  ref: docs
                  token: ${{ secrets.CAUSALABS_PAT }}
                  path: ./causadb-server-docs

            # Copy contents of causadb-server-docs to the ./docs/reference/api directory
            - name: Move API docs to site
              run: cp -r ./causadb-server-docs/* ./docs/reference/api/

            # Pull the latest doc pages from the causadb-python repository
            - name: Checkout causadb-python repository
              uses: actions/checkout@v3
              with:
                  repository: causalabs/causadb-python
                  ref: docs
                  token: ${{ secrets.CAUSALABS_PAT }}
                  path: ./causadb-python-docs

            # Copy contents of causadb-python-docs to the ./docs/reference/python directory
            - name: Move Python docs to site
              run: cp -r ./causadb-python-docs/* ./docs/reference/python/

            # # Pull the latest doc pages from the causadb-node repository
            # - name: Checkout causadb-node repository
            #   uses: actions/checkout@v3
            #   with:
            #       repository: causalabs/causadb-node
            #       ref: docs
            #       token: ${{ secrets.CAUSALABS_PAT }}
            #       path: ./causadb-node-docs

            # - name: Move Node docs to site
            #   run: cp -r ./causadb-node-docs/* ./docs/reference/node/

            - name: Build site
              run: yarn build

            # Popular action to deploy to GitHub Pages:
            # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
            - name: Push to docs branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  # Build output to publish to the `gh-pages` branch:
                  publish_dir: ./build
                  publish_branch: docs
                  user_name: github-actions[bot]
                  user_email: 41898282+github-actions[bot]@users.noreply.github.com
